Pre-release update
criteo-cookbooks/python3 pull request #1
Opened 2022-08-23 15:51 UTC by achamo

Fixing linting issue
FIxing testing issue
Fixing CI configuration

The cookbook was not released because all of them

2022-08-25 07:57 UTC, josqu4red approved these changes

2022-08-25 11:04 UTC, Annih requested changes

2022-08-25 11:04 UTC, Annih commented on .github/workflows/criteo-cookbooks-ci.yml
> +                   'python3-chef-14-centos-7', 'python3-chef-14-centos-8']
You keep `python3-chef-14-centos-8` here but you have excluded the `centos-8` platform in the Chef-14 suite due to DNF issue on Chef < 16

2022-08-26 08:25 UTC, Annih approved these changes

2022-09-05 13:03 UTC, merged